version: '3.8'
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    networks:
      - mynetwork
      - test
    # environment:
    #   - POSTGRES_HOST=192.168.1.7
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=***REMOVED***
    volumes:
      - ./api/logs:/usr/src/app/logs # Map host directory to container directory
    depends_on:
      - redis

  ui:
    build: ./next-ui
    container_name: ui
    ports:
      - '3000:3000'
    # environment:
    #   - PORT=3000
    #   - HOST=0.0.0.0
    stdin_open: true
    networks:
      - test

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_c
    platform: linux/amd64  
    ports:
      - '6379:6379'
    networks:
      - mynetwork
      - test

networks:
  test:
    driver: bridge
  mynetwork:
    driver: bridge