/*
 * © 2025 PVP Inc.
 * Source available under non-commercial license.
 * Commercial use prohibited without a commercial license.
 * See LICENSE.md file or contact licensing@pvp.co.jp
 */

require('dotenv').config()

module.exports = {
  TTL: process.env.TTL,
  STRING: process.env.STRING,
  SETS: process.env.SETS,
  SORTED_SETS: process.env.SORTED_SETS,
  HASH: process.env.HASH,
  JSON: process.env.JSON,
  ITEM: process.env.ITEM,
  INFO: process.env.INFO,
  LIST: process.env.LIST,
  FILTERS: process.env.FILTERS,
  TYPE: process.env.TYPE,
  TRASHED: process.env.TRASHED,
  DELETED: process.env.DELETED,
  SHARED_WITH: process.env.SHARED_WITH,
  OWNER: process.env.OWNER,
  GENERAL_ACCESS: process.env.GENERAL_ACCESS,
  FILES: process.env.FILES,
  FILE_COUNT: process.env.FILE_COUNT,
  ITEM_LIMIT: process.env.ITEM_LIMIT,
  DRIVE_STRUCTURE: process.env.DRIVE_STRUCTURE,
  DIRECT_PATH: process.env.DIRECT_PATH,
  ALL_DRIVES_DATA: process.env.ALL_DRIVES_DATA,
  DRIVE: process.env.DRIVE,
  INITIAL_DEPTH: process.env.INITIAL_DEPTH,
  PERSONAL_DRIVE: process.env.PERSONAL_DRIVE,
  SHARED_DRIVE: process.env.SHARED_DRIVE,
  DOMAIN_TEST: process.env.DOMAIN_TEST,
  SUPER_ADMIN_EMAIL: process.env.SUPER_ADMIN_EMAIL,
  CLIENT_SERVICE_ACCOUNT_EMAIL: process.env.CLIENT_SERVICE_ACCOUNT_EMAIL,
  PORT: process.env.PORT || 4000,
  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  POSTGRES_HOST: process.env.POSTGRES_HOST,
  POSTGRES_PORT: process.env.POSTGRES_PORT,
  POSTGRES_USER: process.env.POSTGRES_USER,
  POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD,
  POSTGRES_DB: process.env.POSTGRES_DB,
  REDIS_HOST: process.env.REDIS_HOST,
  REDIS_PORT: process.env.REDIS_PORT,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  REDIRECT_URI: 'http://localhost:4000/project/initiate-project',
  SCOPES: [
    'https://www.googleapis.com/auth/cloud-platform',
    'https://www.googleapis.com/auth/admin.directory.user',
    'https://www.googleapis.com/auth/admin.directory.domain',
    'https://www.googleapis.com/auth/activity',
    'https://www.googleapis.com/auth/drive.activity',
    'https://www.googleapis.com/auth/drive.activity.readonly',
    'https://www.googleapis.com/auth/drive.metadata.readonly',
    'https://www.googleapis.com/auth/admin.directory.group',
    'https://www.googleapis.com/auth/admin.directory.group.readonly',
    'https://www.googleapis.com/auth/admin.reports.audit.readonly',
    'https://www.googleapis.com/auth/apps.groups.settings',
    'https://www.googleapis.com/auth/admin.directory.user.security',
    'https://www.googleapis.com/auth/admin.directory.rolemanagement',
    'https://www.googleapis.com/auth/admin.directory.orgunit',
  ],
  CRYPTO: process.env.CRYPTO,
  PROJECT_NAME: process.env.PROJECT_NAME,
}
